# Generated by Django 4.0.5 on 2022-07-01 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=252, verbose_name='nombre')),
                ('tipo', models.PositiveIntegerField(choices=[('text', 'Text'), ('date', 'Date'), ('datetime-local', 'Datetime'), ('textarea', 'Text area'), ('select', 'Select'), ('number', 'Number'), ('checkbox', 'Check box'), ('time', 'Time')], verbose_name='field type')),
                ('values_select', models.TextField(blank=True, help_text='This parameter is required when the field is of type select.', null=True, verbose_name='Values of select')),
                ('is_required', models.BooleanField(verbose_name='Required field?')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='campaigns.form')),
            ],
            options={
                'verbose_name': 'FieldForm',
                'verbose_name_plural': 'FieldsForm',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name="name's ")),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.form')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
