# Generated by Django 4.0.5 on 2022-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('datetime-local', 'Datetime'), ('textarea', 'Text area'), ('select', 'Select'), ('number', 'Number'), ('checkbox', 'Check box'), ('time', 'Time')], max_length=16, verbose_name='field type'),
        ),
    ]
