# Generated by Django 4.0.5 on 2022-07-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='management',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='management',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='management',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managements.originmanagement'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.formfield'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_fields', to='managements.management'),
        ),
    ]
